# Generated by Django 4.1.3 on 2022-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semilla',
            name='precio',
            field=models.FloatField(),
        ),
    ]
