# Generated by Django 4.1.3 on 2022-11-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eSeeds', '0002_alter_semilla_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Semilla',
            new_name='Producto',
        ),
    ]
