# Generated by Django 4.1.3 on 2022-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSeeds', '0004_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(help_text='Formato de fecha: AAAA-MM-DD'),
        ),
    ]
