# Generated by Django 4.1.3 on 2022-12-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eSeeds', '0005_alter_cliente_fechanacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fechaNacimiento',
            new_name='nacimiento',
        ),
    ]
