# Generated by Django 4.1.3 on 2022-12-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSeeds', '0007_atencioncliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('poblacion', models.CharField(max_length=50)),
                ('postal', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
