# Generated by Django 4.1.3 on 2022-12-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eSeeds', '0010_pedido_id_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_pedido',
        ),
    ]
