# Generated by Django 4.1.3 on 2022-12-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eSeeds', '0011_alter_producto_imagen'),
        ('eSeeds', '0012_alter_atencioncliente_tipo_consulta'),
    ]

    operations = [
    ]
